apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-cicd-demo-deployment
  labels:
    app: eks-cicd-demo
  namespace: "$(NAMESPACE_NAME)"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-cicd-demo
  template:
    metadata:
      labels:
        app: eks-cicd-demo
      namespace: "$(NAMESPACE_NAME)"
    spec:
      containers:
        - name: eks-cicd-demo
          image: CONTAINER_IMAGE         
          ports:
            - containerPort: 80